---
# 监控
stat_addr: "127.0.0.1:12800"
stat_path: "/metrics"

singleRowNums: 2500
readerNums: 1
writerNums: 1

# 输入源
inputs:
  - driver: mysql
    name: k8s-root
    address: "rr-bp1o44o31e1jzxi6x5o.mysql.rds.aliyuncs.com:3306"
    user: "data"
    password: "jSWnS5JLwJhznPyx"
    charset: "utf8mb4"
    only: [
        "himo_micro_staff_prod",
        "himo_manage_auth_prod",
        "himo_micro_store_prod",
        "himo_micro_user_prod",
        "himo_user_auth_prod"
    ]
    dbAlias:
      himo_micro_staff_prod: "himo-micro-staff"
      himo_manage_auth_prod: "himo-micro-manage-auth"
      himo_micro_store_prod: "himo-micro-store"
      himo_micro_user_prod: "himo-micro-user"
      himo_user_auth_prod: "himo-micro-user-auth"
    maxConnNums: 4
# 输出源
output:
  driver: mysql
  name: output-test
  address: "pxc-hzry9e7ergg5xt.public.polarx.rds.aliyuncs.com:3306"
  user: "sync_lenye"
  password: "yq7bZcYRoPG6FgEgmJ"
  charset: "utf8mb4"
  maxConnNums: 10
  only: [
    "himo_micro_staff_prod",
    "himo_manage_auth_prod",
    "himo_micro_store_prod",
    "himo_micro_user_prod",
    "himo_user_auth_prod"
  ]
#  exclude: ["himo-micro-staff"]
#  address: "127.0.0.1:13306"
#  user: "root"
#  password: "password"
# 提取配置

# 过滤配置
filters:
